LuuNa-JD/monsters_market

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Test d'ajout de cards sur la homepage
> adding cards on home page

- app/controllers/monsters_controller.rb
- app/models/monster.rb
- app/models/user.rb
- app/views/monsters/index.html.erb
- config/routes.rb
- db/migrate/20231028200301_create_monsters.rb
- db/schema.rb
- test/controllers/monsters_controller_test.rb
- test/models/monster_test.rb
great monster model and controller
> add a monster mvc with a controller and a view and setting the routes

- app/controllers/monsters_controller.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- db/schema.rb
Adding design to devise pages login, signup and more...
> bootstraping devise pages

- app/controllers/monsters_controller.rb
- app/controllers/pages_controller.rb
- app/views/monsters/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/schema.rb
> Monster form

- app/assets/stylesheets/pages/_index-monster.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/monsters/index.html.erb
- app/views/monsters/show.html.erb
- config/routes.rb
> new monsters views + update routes

- app/controllers/monsters_controller.rb
- app/views/monsters/new.html.erb
- config/routes.rb
> debug monster form

- app/views/monsters/new.html.erb
>  association bug correction

- app/assets/stylesheets/pages/_home.scss
- app/controllers/monsters_controller.rb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> new navbar and homepage with back end ok

- app/assets/stylesheets/pages/_index-monster.scss
- app/views/monsters/index.html.erb
> index page with back end ok

- app/views/bookings/index.html.erb
- app/views/shared/_navbar.html.erb
creating  dashboard for user and vendor
> creating  dashboard for user and vendor

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- app/views/monsters/show.html.erb
- config/routes.rb
patch bug in booking controller, routes and dashboard
> patch bug in booking controller, routes and dashboard

- app/views/bookings/index.html.erb
- app/views/layouts/application.html.erb
- app/views/monsters/index.html.erb
- app/views/pages/home.html.erb
patch for homepage and monsters index
> patch for homepage and monsters index

- app/views/bookings/index.html.erb
- app/views/monsters/index.html.erb
> Bookings front patch

- app/views/bookings/index.html.erb
> patch dashbord bookings

- app/views/monsters/show.html.erb
> booking confirmation

- app/assets/stylesheets/pages/_show-monster.scss
- app/views/monsters/show.html.erb
modifications dans la show de monster
> modifications dans la show de monster

- app/views/bookings/_edit.html.erb
- app/views/bookings/index.html.erb
Patch pour le tableau de booking
> Patch pour le tableau de booking

- app/controllers/bookings_controller.rb
- app/views/bookings/_modal.html.erb
- app/views/bookings/_non_vendor_table.html.erb
- app/views/bookings/_vendor_table.html.erb
- app/views/bookings/index.html.erb
Refactorisation de l'index de booking
> Refactorisation de l'index de booking

- app/assets/stylesheets/pages/_home.scss
- app/views/bookings/index.html.erb
- app/views/pages/home.html.erb
> Home css patching

- app/views/monsters/edit.html.erb
- app/views/monsters/show.html.erb
> patch pour show de monster

- app/controllers/bookings_controller.rb
- app/views/monster_mailer/booking_confirmation_email.html.erb
- app/views/monster_mailer/reservation_email.html.erb
> new design for mails

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_index-booking.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
Ajout d'une pagination sur l'index de bookings
> Ajout d'une pagination sur l'index de bookings

- app/assets/stylesheets/pages/_show-monster.scss
- app/views/monsters/show.html.erb
> add reviews to monster
